# example of a machine specific settings
windows:
  mainwindow:
    kwargs:
      confirm_exit: false

settings:
  tool_table.custom:
    value_type: dict
    default_value: {
      path_color: list,
      holder_model: str,
      tool_model: str,
      flutes: int,
      chip_load.rpm: int,
      chip_load.feed: int
    }

