# example of a machine specific settings
windows:
  mainwindow:
    kwargs:
      confirm_exit: false

settings:
  tool_table.custom:
    default_value: {
      holder_model: true,
      tool_model: true,
      flutes: true,
      chip_load.rpm: true,
      chip_load.feed: true
    }
    value_type: dict

